### ISSUE TITLE
MQTT not working

### ISSUE THREAD

**Issue by haiduc32** [mishacucicea/RedAlert#1]
MQTT crashes the ESP8266.

I have a few leads:
https://github.com/knolleary/pubsubclient/issues/84
https://github.com/marvinroger/homie-esp8266/issues/42
https://gist.github.com/chaeplin/3223074601733fa46d4a

the problem might be because:
1. I'm not using secure wifi
2. might need to do something with the certificate verification

**Comment by haiduc32** [comment]
Done!!!

**Comment by mishacucicea** [comment]
Nice :D
